name: comet
description: UI Library for comet project. Static Site Generator made with Flutter.
version: 0.3.1
repository: https://github.com/rubydog-jp/comet

environment:
  sdk: ^3.0.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  html: ^0.15.4
  intl: ^0.18.1
  markdown: ^7.1.1
  markdown_widget: ^2.3.1
  flutter_highlighting: ^0.9.0+11.8.0
  scroll_to_index: ^3.0.1
  visibility_detector: ^0.4.0+2
  google_fonts: ^6.1.0
  go_router: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
