name: comet_cli
description: A command-line interface for comet project. Static Site Generator made with Flutter.
version: 0.3.1
repository: https://github.com/rubydog-jp/comet

executables:
  comet: comet_cli

environment:
  sdk: ^3.1.0

dependencies:
  path: ^1.8.3
  args: ^2.4.2
  git: ^2.2.1
  http: ^1.1.0
  archive: ^3.4.6
  yaml: ^3.1.2
  watcher: ^1.1.0
  base32: ^2.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
